#!/bin/sh
# Git hook to run tests after merging or pulling changes
# Usage: configure Git to use this hook by running:
#   git config core.hooksPath .githooks

echo "Running tests after merge..."
npm test
